//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oda_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgmap_district
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bgmap_district()
        {
            this.bgmap_commune = new HashSet<bgmap_commune>();
        }
    
        public int gid { get; set; }
        public string ten_huyen { get; set; }
        public Nullable<int> tinh_id { get; set; }
        public Nullable<int> danso { get; set; }
        public Nullable<float> dinhmucsudungnuoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bgmap_commune> bgmap_commune { get; set; }
    }
}
