//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oda_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class iw_congtrinhcapnuocsach
    {
        public long id { get; set; }
        public System.Guid mahieu { get; set; }
        public string ten { get; set; }
        public Nullable<int> xa_id { get; set; }
        public Nullable<int> huyen_id { get; set; }
        public Nullable<int> tinh_id { get; set; }
        public Nullable<int> httn_id { get; set; }
        public Nullable<int> loaict_id { get; set; }
        public Nullable<int> dvql_id { get; set; }
        public Nullable<int> luuvucsong_id { get; set; }
        public string nguon_goc { get; set; }
        public string donvi_tinh { get; set; }
        public Nullable<int> loai_taisan_id { get; set; }
        public Nullable<int> nam_xaydung { get; set; }
        public Nullable<int> nam_khaithac { get; set; }
        public Nullable<int> nam_bangiao { get; set; }
        public Nullable<float> dientich_dat { get; set; }
        public Nullable<float> dientich_san { get; set; }
        public Nullable<float> nguyen_gia { get; set; }
        public Nullable<float> tyle_haomon { get; set; }
        public Nullable<float> giatri_conlai { get; set; }
        public Nullable<bool> tinhtrang_taisan { get; set; }
        public Nullable<int> song_id { get; set; }
        public string ma_qhns { get; set; }
        public Nullable<int> type_nguyengia { get; set; }
        public Nullable<int> isdangxaydung { get; set; }
        public Nullable<float> gtcanhbao_mnchancongtrinh { get; set; }
        public Nullable<System.Guid> httn_config { get; set; }
        public Nullable<float> nangluc_lua { get; set; }
        public Nullable<float> nangluc_raumau { get; set; }
        public Nullable<float> nangluc_cndaingay { get; set; }
        public Nullable<float> nangluc_thuysan { get; set; }
        public Nullable<float> kinhdo { get; set; }
        public Nullable<float> vido { get; set; }
        public Nullable<System.Guid> duan_ref { get; set; }
        public Nullable<System.Guid> hethong_ref { get; set; }
        public string diadiem { get; set; }
        public Nullable<float> lat { get; set; }
        public Nullable<float> lon { get; set; }
        public string nguoncap { get; set; }
        public Nullable<int> loaicongtrinh_id { get; set; }
        public Nullable<float> dungtich { get; set; }
        public Nullable<int> songuoicap { get; set; }
        public Nullable<float> congsuatcapnuoc { get; set; }
        public string hethongxuly { get; set; }
        public string hethongbechua { get; set; }
        public string hethongphanphoi { get; set; }
        public string chatluongnuoccap { get; set; }
        public Nullable<float> gianuoc { get; set; }
        public string namxaydung { get; set; }
        public string namduvaosudung { get; set; }
        public Nullable<int> hientranghoatdong_id { get; set; }
        public string tinhtranghuhong { get; set; }
        public string dexuatgiaiphapdautu { get; set; }
        public Nullable<int> songuoitangthem { get; set; }
        public Nullable<float> uockinhphidautu { get; set; }
        public string chudautu { get; set; }
        public string duan { get; set; }
        public string donviquanly { get; set; }
        public Nullable<float> songuoivanhanh { get; set; }
        public Nullable<int> cn_namduavaosudung { get; set; }
        public Nullable<float> cn_dientichdat { get; set; }
        public Nullable<float> cn_dientichsansudung { get; set; }
        public Nullable<float> cn_congsuatthietke { get; set; }
        public Nullable<float> cn_congsuatthucte { get; set; }
        public Nullable<int> cn_sohosudungthietke { get; set; }
        public Nullable<int> cn_sohosudungthucte { get; set; }
        public Nullable<float> cn_giatritaisannguyengia { get; set; }
        public Nullable<float> cn_giatritaisangtcl { get; set; }
        public Nullable<int> cn_tinhtrangtaisan { get; set; }
        public string cn_hinhthucxuly { get; set; }
    }
}
