//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oda_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class iw_dam
    {
        public long id { get; set; }
        public System.Guid mahieu { get; set; }
        public string ten { get; set; }
        public Nullable<int> xa_id { get; set; }
        public Nullable<int> huyen_id { get; set; }
        public Nullable<int> tinh_id { get; set; }
        public Nullable<int> httn_id { get; set; }
        public Nullable<int> loaict_id { get; set; }
        public Nullable<int> dvql_id { get; set; }
        public Nullable<int> luuvucsong_id { get; set; }
        public string nguon_goc { get; set; }
        public string donvi_tinh { get; set; }
        public Nullable<int> loai_taisan_id { get; set; }
        public Nullable<int> nam_xaydung { get; set; }
        public Nullable<int> nam_khaithac { get; set; }
        public Nullable<int> nam_bangiao { get; set; }
        public Nullable<float> dientich_dat { get; set; }
        public Nullable<float> dientich_san { get; set; }
        public Nullable<float> nguyen_gia { get; set; }
        public Nullable<float> tyle_haomon { get; set; }
        public Nullable<float> giatri_conlai { get; set; }
        public Nullable<bool> tinhtrang_taisan { get; set; }
        public Nullable<int> song_id { get; set; }
        public string ma_qhns { get; set; }
        public Nullable<int> type_nguyengia { get; set; }
        public Nullable<int> isdangxaydung { get; set; }
        public Nullable<float> gtcanhbao_mnchancongtrinh { get; set; }
        public Nullable<System.Guid> httn_config { get; set; }
        public Nullable<float> nangluc_lua { get; set; }
        public Nullable<float> nangluc_raumau { get; set; }
        public Nullable<float> nangluc_cndaingay { get; set; }
        public Nullable<float> nangluc_thuysan { get; set; }
        public Nullable<float> kinhdo { get; set; }
        public Nullable<float> vido { get; set; }
        public Nullable<System.Guid> duan_ref { get; set; }
        public Nullable<System.Guid> hethong_ref { get; set; }
        public Nullable<int> slg_cong { get; set; }
        public Nullable<int> congnghe_thicong { get; set; }
        public string cap_congtrinh { get; set; }
        public string hinhthuc_dap { get; set; }
        public Nullable<float> caotrinh_dinhdap { get; set; }
        public Nullable<float> caotrinh_tuongcs { get; set; }
        public Nullable<float> chieudai_dap { get; set; }
        public Nullable<float> chieucao_dap { get; set; }
        public Nullable<float> chieurong_dap { get; set; }
        public string heso_mai_thgluu { get; set; }
        public string heso_mai_haluu { get; set; }
        public string vatlieu_mai_thgluu { get; set; }
        public string vatlieu_mai_haluu { get; set; }
        public Nullable<bool> htr_mai_thgluu { get; set; }
        public Nullable<bool> htr_thamnuoc_nang { get; set; }
        public Nullable<bool> htr_thamnuoc_nhe { get; set; }
        public string tbi_tieunuoc { get; set; }
        public string diadiem { get; set; }
        public Nullable<int> loaidap { get; set; }
        public Nullable<int> vatlieu_dap { get; set; }
        public Nullable<System.Guid> reservoir_id { get; set; }
        public Nullable<int> sodapphu { get; set; }
        public bool kienco { get; set; }
        public Nullable<float> chieucao_lonnhat { get; set; }
        public string caotrinhco_thuongluu { get; set; }
        public Nullable<float> chieurongco_thuongluu { get; set; }
        public string giacomai_thuongluu { get; set; }
        public string caotrinhco_haluu { get; set; }
        public Nullable<float> chieurongco_haluu { get; set; }
        public string giacomai_haluu { get; set; }
        public string dongdachanmai { get; set; }
        public string caotrinh_dongda { get; set; }
        public Nullable<float> chieurong_dongda { get; set; }
        public string hesomai_thgluu_haluu { get; set; }
        public string xulychongtham { get; set; }
        public Nullable<System.Guid> dubaolu_id { get; set; }
        public string ghichu { get; set; }
        public Nullable<long> temp_id { get; set; }
        public string donviquanly { get; set; }
        public string lakecode_tlvn { get; set; }
        public string damcode_tlvn { get; set; }
        public string ketcaucongtrinh { get; set; }
        public string caotrinhnguong { get; set; }
        public string hientrang { get; set; }
        public string tansuattieu { get; set; }
        public string tansuattuoi { get; set; }
        public string tieuchuanthoatlu { get; set; }
        public string dienthoai { get; set; }
        public string quytrinhvanhanh { get; set; }
        public string vatlieugiaco { get; set; }
        public string nhiemvu { get; set; }
    }
}
