//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oda_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class iw_flood_spillway
    {
        public long id { get; set; }
        public System.Guid mahieu { get; set; }
        public string ten { get; set; }
        public Nullable<int> xa_id { get; set; }
        public Nullable<int> huyen_id { get; set; }
        public Nullable<int> tinh_id { get; set; }
        public Nullable<int> httn_id { get; set; }
        public Nullable<int> loaict_id { get; set; }
        public Nullable<int> dvql_id { get; set; }
        public Nullable<int> luuvucsong_id { get; set; }
        public string nguon_goc { get; set; }
        public string donvi_tinh { get; set; }
        public Nullable<int> loai_taisan_id { get; set; }
        public Nullable<int> nam_xaydung { get; set; }
        public Nullable<int> nam_khaithac { get; set; }
        public Nullable<int> nam_bangiao { get; set; }
        public Nullable<float> dientich_dat { get; set; }
        public Nullable<float> dientich_san { get; set; }
        public Nullable<float> nguyen_gia { get; set; }
        public Nullable<float> tyle_haomon { get; set; }
        public Nullable<float> giatri_conlai { get; set; }
        public Nullable<bool> tinhtrang_taisan { get; set; }
        public Nullable<int> song_id { get; set; }
        public string ma_qhns { get; set; }
        public Nullable<int> type_nguyengia { get; set; }
        public Nullable<int> isdangxaydung { get; set; }
        public Nullable<float> gtcanhbao_mnchancongtrinh { get; set; }
        public Nullable<System.Guid> httn_config { get; set; }
        public Nullable<float> nangluc_lua { get; set; }
        public Nullable<float> nangluc_raumau { get; set; }
        public Nullable<float> nangluc_cndaingay { get; set; }
        public Nullable<float> nangluc_thuysan { get; set; }
        public Nullable<float> kinhdo { get; set; }
        public Nullable<float> vido { get; set; }
        public Nullable<System.Guid> duan_ref { get; set; }
        public Nullable<System.Guid> hethong_ref { get; set; }
        public string hinhthuc_tran { get; set; }
        public string hinhthuc_tieunang { get; set; }
        public string hinhthuc_dongmo { get; set; }
        public Nullable<float> luulgxa_tke { get; set; }
        public Nullable<float> luulgxa_ktra { get; set; }
        public Nullable<float> ct_dinhtran { get; set; }
        public Nullable<float> ct_nguongtran { get; set; }
        public Nullable<float> chieurong_tran { get; set; }
        public Nullable<float> cotnuoc_tran { get; set; }
        public string tuyen { get; set; }
        public Nullable<float> domo_max { get; set; }
        public string ketcau_tran { get; set; }
        public string hientrang { get; set; }
        public Nullable<bool> tran_hongnang { get; set; }
        public Nullable<bool> tran_canmr { get; set; }
        public Nullable<bool> codangxa { get; set; }
        public Nullable<float> luulg_xa { get; set; }
        public string tbi_tieunang { get; set; }
        public Nullable<int> nam_suachua { get; set; }
        public Nullable<int> sokhoangtran { get; set; }
        public Nullable<float> berong_khoang { get; set; }
        public Nullable<bool> cotransuco { get; set; }
        public string lytrinh { get; set; }
        public Nullable<int> vatlieu_xaydung { get; set; }
        public string vitri { get; set; }
        public Nullable<float> chieucao_tran { get; set; }
        public Nullable<float> cotnuoc_tke { get; set; }
        public string trangthai { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.Guid> reservoir_id { get; set; }
        public string soluong_kichthuoc { get; set; }
        public Nullable<float> caotrinhday_tieunang { get; set; }
        public Nullable<float> chieudai_tieunang { get; set; }
        public Nullable<float> chieurong_tieunang { get; set; }
        public Nullable<int> loaitran { get; set; }
        public Nullable<int> giaidoan_thuchien_id { get; set; }
        public Nullable<int> canal_id { get; set; }
        public string diadiem { get; set; }
        public string vatlieuxd { get; set; }
        public Nullable<double> chieudai { get; set; }
        public Nullable<int> captran { get; set; }
        public Nullable<System.Guid> dam_id { get; set; }
        public string lakecode_tlvn { get; set; }
        public string matran_tlvn { get; set; }
        public Nullable<int> temp_id { get; set; }
    }
}
