//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oda_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class iw_reservoir_stations
    {
        public int id { get; set; }
        public Nullable<System.Guid> reservoir_id { get; set; }
        public Nullable<System.Guid> stations_id { get; set; }
        public Nullable<float> trongso { get; set; }
        public bool istramhadu { get; set; }
        public Nullable<int> stt { get; set; }
        public string bangdulieu { get; set; }
        public Nullable<System.Guid> dbl_tramanhxa { get; set; }
        public bool istramdomua { get; set; }
        public Nullable<bool> isdubaolu { get; set; }
    }
}
