//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oda_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class iw_thongsoquantrac
    {
        public long tskt_id { get; set; }
        public string tskt_command { get; set; }
        public string tskt_ten { get; set; }
        public Nullable<int> tskt_stt { get; set; }
        public Nullable<long> tskt_noisuy_id { get; set; }
        public Nullable<int> tskt_deletedstatus { get; set; }
        public string tskt_maloaithongso { get; set; }
        public string tskt_noisuy_func { get; set; }
        public Nullable<float> tskt_nguong_min { get; set; }
        public Nullable<float> tskt_nguong_max { get; set; }
        public Nullable<System.Guid> works_id { get; set; }
        public Nullable<int> tskt_thongso_scada { get; set; }
        public Nullable<int> tskt_scada_id { get; set; }
        public string tskt_unit { get; set; }
        public Nullable<bool> tskt_nhaplieuthucong { get; set; }
        public Nullable<float> tskt_giatrithietke { get; set; }
        public Nullable<int> tskt_tuyenquantrac_ref { get; set; }
        public Nullable<int> tskt_isblock { get; set; }
        public Nullable<bool> is_antoanhochua { get; set; }
        public Nullable<bool> is_hethongtuoi { get; set; }
        public Nullable<bool> is_qlxdct { get; set; }
        public Nullable<System.Guid> tskt_key { get; set; }
        public Nullable<System.DateTime> tskt_dateblock { get; set; }
        public string tskt_userblock { get; set; }
        public string tskt_noteblock { get; set; }
        public Nullable<int> dubaolu_stt { get; set; }
        public string func_tinhxuoi { get; set; }
        public string func_tinhnguoc { get; set; }
        public Nullable<long> func_tskt_ketqua { get; set; }
        public string func_tskt_input { get; set; }
        public Nullable<int> cotanhxa { get; set; }
        public string nguon_dulieu { get; set; }
        public string ma_dulieu { get; set; }
        public bool issum { get; set; }
        public Nullable<float> giatrigioihan { get; set; }
        public Nullable<float> giatrigioihannen { get; set; }
        public Nullable<float> giatrigioihankeo { get; set; }
    }
}
