//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oda_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class khudancu3857
    {
        public int gid { get; set; }
        public Nullable<long> objectid { get; set; }
        public string manhandang { get; set; }
        public Nullable<System.DateTime> ngaythunha { get; set; }
        public Nullable<System.DateTime> ngaycapnha { get; set; }
        public string madoituong { get; set; }
        public string ten { get; set; }
        public Nullable<int> loaiphubem { get; set; }
        public Nullable<decimal> shape_leng { get; set; }
        public Nullable<decimal> shape_area { get; set; }
    }
}
