//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oda_test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class odaEntities : DbContext
    {
        public odaEntities()
            : base("name=odaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bgmap_commune> bgmap_commune { get; set; }
        public virtual DbSet<bgmap_district> bgmap_district { get; set; }
        public virtual DbSet<bgmap_province> bgmap_province { get; set; }
        public virtual DbSet<iw_boviaviahe> iw_boviaviahe { get; set; }
        public virtual DbSet<iw_canal> iw_canal { get; set; }
        public virtual DbSet<iw_coc> iw_coc { get; set; }
        public virtual DbSet<iw_congtrinhcapnuocsach> iw_congtrinhcapnuocsach { get; set; }
        public virtual DbSet<iw_dam> iw_dam { get; set; }
        public virtual DbSet<iw_denchieusang> iw_denchieusang { get; set; }
        public virtual DbSet<iw_diemngap> iw_diemngap { get; set; }
        public virtual DbSet<iw_duongong> iw_duongong { get; set; }
        public virtual DbSet<iw_flood_spillway> iw_flood_spillway { get; set; }
        public virtual DbSet<iw_gieng> iw_gieng { get; set; }
        public virtual DbSet<iw_hoga> iw_hoga { get; set; }
        public virtual DbSet<iw_hotrongcay> iw_hotrongcay { get; set; }
        public virtual DbSet<iw_irrigation_sewer> iw_irrigation_sewer { get; set; }
        public virtual DbSet<iw_irrigation_works> iw_irrigation_works { get; set; }
        public virtual DbSet<iw_nhamayxulynuocthai> iw_nhamayxulynuocthai { get; set; }
        public virtual DbSet<iw_pump_station> iw_pump_station { get; set; }
        public virtual DbSet<iw_reservoir> iw_reservoir { get; set; }
        public virtual DbSet<iw_reservoir_stations> iw_reservoir_stations { get; set; }
        public virtual DbSet<iw_thongsoquantrac> iw_thongsoquantrac { get; set; }
        public virtual DbSet<iw_timduong> iw_timduong { get; set; }
        public virtual DbSet<iw_trucuuhoa> iw_trucuuhoa { get; set; }
        public virtual DbSet<iw_vuotnoi> iw_vuotnoi { get; set; }
        public virtual DbSet<khudancu3857> khudancu3857 { get; set; }
        public virtual DbSet<monitoring_data> monitoring_data { get; set; }
        public virtual DbSet<sys_function_role> sys_function_role { get; set; }
        public virtual DbSet<sys_role> sys_role { get; set; }
        public virtual DbSet<sys_thongso_kythuat> sys_thongso_kythuat { get; set; }
        public virtual DbSet<sys_thongso_kythuat_detail> sys_thongso_kythuat_detail { get; set; }
        public virtual DbSet<sys_user_ho> sys_user_ho { get; set; }
        public virtual DbSet<sys_user_httn> sys_user_httn { get; set; }
        public virtual DbSet<tbl_danhmuc_duan> tbl_danhmuc_duan { get; set; }
        public virtual DbSet<tbl_danhmuc_hethong> tbl_danhmuc_hethong { get; set; }
        public virtual DbSet<tbl_duytubaoduong> tbl_duytubaoduong { get; set; }
        public virtual DbSet<tbl_tutailieu_files> tbl_tutailieu_files { get; set; }
    }
}
