//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oda_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class monitoring_data
    {
        public long data_id { get; set; }
        public long tskt_id { get; set; }
        public System.DateTime data_thoigian { get; set; }
        public System.DateTime data_thoigiancapnhat { get; set; }
        public Nullable<float> data_giatri_sothuc { get; set; }
        public Nullable<int> data_giatri_songuyen { get; set; }
        public string data_giatri_chuoi { get; set; }
        public Nullable<int> data_canhbao { get; set; }
        public Nullable<bool> data_seesaw { get; set; }
        public Nullable<int> config_warning_id { get; set; }
        public string createdby { get; set; }
        public Nullable<bool> data_istonghop { get; set; }
        public string data_nguonsolieu { get; set; }
    }
}
