//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oda_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_role
    {
        public long role_id { get; set; }
        public Nullable<int> role_cq_id { get; set; }
        public string role_ten { get; set; }
        public Nullable<int> role_stt { get; set; }
        public string role_nguoitao { get; set; }
        public string role_ma { get; set; }
        public Nullable<int> role_type { get; set; }
    }
}
