//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oda_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_user_ho
    {
        public int id { get; set; }
        public Nullable<int> ho_id { get; set; }
        public Nullable<System.Guid> user_id { get; set; }
        public Nullable<System.Guid> ho_uuid { get; set; }
        public Nullable<int> ho_stt { get; set; }
        public Nullable<bool> ho_hienthi { get; set; }
        public Nullable<int> loai_congtrinh { get; set; }
    }
}
