//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oda_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_thongso_kythuat_detail
    {
        public long tsdt_id { get; set; }
        public Nullable<int> tsdt_ts_id { get; set; }
        public Nullable<System.Guid> tsdt_mahieu { get; set; }
        public string tsdt_value { get; set; }
        public Nullable<bool> tsdt_display { get; set; }
        public Nullable<int> tsdt_orderby { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> last_modified_at { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<int> deleted_status { get; set; }
    }
}
