//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oda_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_thongso_kythuat
    {
        public long ts_id { get; set; }
        public string ts_name { get; set; }
        public Nullable<int> ts_form { get; set; }
        public Nullable<int> ts_parentid { get; set; }
        public string ts_map_table { get; set; }
        public string ts_map_column { get; set; }
        public string ts_field_table { get; set; }
        public string ts_field_id { get; set; }
        public string ts_field_name { get; set; }
        public string ts_field_where { get; set; }
        public string ts_field_order { get; set; }
        public Nullable<int> ts_orderby { get; set; }
        public Nullable<int> ts_type { get; set; }
        public Nullable<int> ts_data_type { get; set; }
        public string ts_unit { get; set; }
        public Nullable<bool> ts_default { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> last_modified_at { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<int> deleted_status { get; set; }
        public string ts_hethong { get; set; }
    }
}
